// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwlbifrvpaeekwmohibp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13bGJpZnJ2cGFlZWt3bW9oaWJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxODE4ODcsImV4cCI6MjA3MDc1Nzg4N30.2C5jRZJBQjaagv22kf7WLBQzeQN9iW9cQzKvwhg4hEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});